name: CI
on: [push]
jobs:
  build:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Load env secrets in a temp file
        run: echo "DATABASE_URL=\"$DATABASE_URL\"" >> ${{ runner.temp }}/.env.test

      - name: Test
        run: npx dotenv -e ${{ runner.temp }}/.env.test -- jest
